package com.myspace1.rhpam_homework;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HOA implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "HOA Name")
	private java.lang.String HOAName;
	@org.kie.api.definition.type.Label(value = "HOA Meeting Date")
	private java.util.Date HOAMeetingDate;
	@org.kie.api.definition.type.Label(value = "HOA Status")
	private java.lang.String HOAStatus;

	public HOA() {
	}

	public java.lang.String getHOAName() {
		return this.HOAName;
	}

	public void setHOAName(java.lang.String HOAName) {
		this.HOAName = HOAName;
	}

	public java.util.Date getHOAMeetingDate() {
		return this.HOAMeetingDate;
	}

	public void setHOAMeetingDate(java.util.Date HOAMeetingDate) {
		this.HOAMeetingDate = HOAMeetingDate;
	}

	public java.lang.String getHOAStatus() {
		return this.HOAStatus;
	}

	public void setHOAStatus(java.lang.String HOAStatus) {
		this.HOAStatus = HOAStatus;
	}

	public HOA(java.lang.String HOAName, java.util.Date HOAMeetingDate,
			java.lang.String HOAStatus) {
		this.HOAName = HOAName;
		this.HOAMeetingDate = HOAMeetingDate;
		this.HOAStatus = HOAStatus;
	}

}