package com.myspace1.rhpam_homework;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "Building Number")
	private java.lang.String buildingNumber;
	@org.kie.api.definition.type.Label(value = "Electrical Number")
	private java.lang.String electricalNumber;

	public OrderDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getBuildingNumber() {
		return this.buildingNumber;
	}

	public void setBuildingNumber(java.lang.String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}

	public java.lang.String getElectricalNumber() {
		return this.electricalNumber;
	}

	public void setElectricalNumber(java.lang.String electricalNumber) {
		this.electricalNumber = electricalNumber;
	}

	public OrderDetails(java.lang.String name, java.lang.String address,
			java.lang.String buildingNumber, java.lang.String electricalNumber) {
		this.name = name;
		this.address = address;
		this.buildingNumber = buildingNumber;
		this.electricalNumber = electricalNumber;
	}

}